# Generated by Django 3.2.6 on 2021-08-29 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(max_length=150, verbose_name='Заголовок новости')),
                ('news_text', models.TextField(verbose_name='Тело новости')),
                ('date', models.DateTimeField(verbose_name='Дата публикации')),
            ],
        ),
    ]
