# Generated by Django 3.2.6 on 2021-09-01 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20210831_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_text',
            field=models.TextField(verbose_name='Тело новости'),
        ),
    ]
