# Generated by Django 3.2.6 on 2021-09-02 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_news_news_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='news_image',
            field=models.ImageField(default='C:\\Users\\Admin\\Desktop\\wip\\images\\image.jpg', upload_to='C:\\Users\\Admin\\Desktop\\wip\\images'),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_text',
            field=models.TextField(verbose_name=''),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_title',
            field=models.CharField(max_length=150, verbose_name=''),
        ),
    ]
